collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.379331
  lightness: 1
  brandColors:
    - '#9C9A8B'
    - '#171D1B'
    - '#44644D'
    - '#A47A16'
    - '#EED240'
  rhythmicContrast: 1
typography_spectrum: 0.2658303
layout_spectrum: 1
name: Superseed
